site:
  title: samuel's portfolio
  url: https://samferos.github.io/portfolio-v2
  start_page: portfolio::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
ui:
  bundle:
    url: ./ui/ui_bundle.zip
    snapshot: true
